version: '3.8'
services:
  web:
    container_name: card_checker
    build: .
    restart: always
    env_file: .env
    command: uvicorn main:app --host 0.0.0.0 --port 3000
    volumes:
     - .:/app
    ports:
      -  3000:3000