version: '3.8'
services:
  web:
    container_name: card_checker
    build: .
    restart: always
    env_file: .env
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 3000"
    volumes:
     - .:/app
    ports:
      -  3000:3000
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: card_checker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypass123
    volumes:
      - ./db:/var/lib/postgresql/data